# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./... -coverprofile=./cover.out -covermode=atomic -coverpkg=./...

    #    https://github.com/marketplace/actions/go-test-coverage
    - name: go-test-coverage
      uses: vladopajic/go-test-coverage@v2.11.1
      with:
        config: ./.testcoverage.yml
        ## when token is not specified (value '') this feature is turned off
        ## in this example badge is created and committed only for main branch
        git-token: ${{ github.ref_name == 'main' && secrets.GITHUB_TOKEN || '' }}
        ## name of branch where badges are stored
        ## ideally this should be orphan branch (see below how to create this branch)
        git-branch: badges
